name: appv1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  fast_rsa: ^3.5.3
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  intl: ^0.18.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - imagens/

